version: '2'
services:
    accuestimatorng2-app:
        image: accuestimatorng2
        external_links:
            - accuestimatorng2-mongodb:mongodb
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=accuestimatorNG2
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    accuestimatorng2-mongodb:
        extends:
            file: mongodb.yml
            service: accuestimatorng2-mongodb
