version: '2'
services:
    accuestimatorng2-mongodb:
        container_name: accuestimatorng2-mongodb
        image: mongo:3.2.10
        ports:
            - "27017:27017"
        # volumes:
        #     - ~/volumes/jhipster/accuestimatorNG2/mongodb/:/data/db/
